= Quarkus Zanzibar

include::./includes/attributes.adoc[]

== Overview

The **Quarkus Zanzibar** extension provides https://zanzibar.academy[Zanzibar] style Fine Grain
Authorization (FGA) capabilities for Quarkus' HTTP subsystems. It integrates with Quarkus'
standard `@PermissionsAllowed` authorization using `ZanzibarPermission` implementations.

The extension only provides the framework and relies on dedicated connectors to communicate with specific
Zanzibar style servers.

Supported APIs and platforms:

- https://openfga.dev[OpenFGA]
- https://authzed.com[Authzed]

== Installation

Adding the `quarkus-zanzibar` extension to your project provides the authorization integration and the APIs
needed to configure permission checks on your resource classes and methods.

To communicate with your selected server API you will need to add the Zanzibar connector for your selected server.

- xref:openfga-connector.adoc#_installation[OpenFGA Connector Installation]
- xref:authzed-connector.adoc#_installation[Authzed Connector Installation]

== Basic Usage

=== Authorization Model

Given a model object `Thing`, and the following simple authorization model that give every `owner` both
`read` and `write` permissions.

[source]
----
include::{examples-dir}/schema.fga[]
----

=== Creating and Accessing Objects

With a suitable authorization model initialized in your selected server, Zanzibar uses `@PermissionsAllowed`
and `ZanzibarPermission` to define the exact authorization details for resource methods.

Using the authorization model from above. The following resource methods allow any user to create new
things but only users with `read` access to fetch them; in this example this will be the `owner` of the `Thing`.

[source,java]
----
include::{examples-dir}/ThingResource.java[]
----
<1> Inject `RelationshipManager` to allow adding & removing relationships.
<2> Inject `Principal` for access to the current user id.
<3> Create a `Relationship` that defines the current user as the `owner` of the newly created `Thing`.
<4> Add the new thing's `owner` relationship to the authorization model.
<5> Use `@PermissionsAllowed` to declare the required relation (`owner`) for the request.
<6> A `ZanzibarPermission` implementation provides the object type (`thing`).
<7> A `ZanzibarPermission` implementation provides the object id (from the method parameter).
<8> For implementations that require it, provide the user object type via `ZanzibarPermission#getUserType()`.

=== More Details

Zanzibar permissions and configuration details are described xref:annotations.adoc[here].

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-zanzibar.adoc[leveloffset=+1, opts=optional]
