
= Quarkus Zanzibar - OpenFGA Connector

include::./includes/attributes.adoc[]

== Overview

The OpenFGA Connector provides access to https://openfga.dev[OpenFGA] server instances or
https://auth0.com/fine-grained-authorization[Auth0's managed authorization platform].
It relies upon the https://github.com/quarkiverse/quarkus-openfga-client[Quarkus OpenFGA Client].

Currently there is no connector specific setup or configuration beyond installing the connector dependency.

Visit the https://github.com/quarkiverse/quarkus-openfga-client[Quarkus OpenFGA Client] project for details on configuring the client to connect to your server or the OpenFGA platform.


[#_installation]
== Installation

To connect to OpenFGA servers you need to add the Zanzibar OpenFGA connector.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.zanzibar</groupId>
    <artifactId>quarkus-zanzibar-openfga</artifactId>
    <version>{project-version}</version>
</dependency>
----

The connector depends on the required `quarkus-zanzibar` extension; its inclusion is optional.

[[extension-configuration-reference]]
== Extension Configuration Reference

Currently there are no specific configuration options for the OpenFGA Connector.
